// <auto-generated />
using System;
using Campuscourse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Campuscourse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250116102258_AddCampusCourseModel")]
    partial class AddCampusCourseModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Campuscourse.Models.CampusCourse.CampusCourseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Annotations")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumStudentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentsEnrolledCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentsInQueueCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CampusCourses");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusCourseNotification.CampusCourseNotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CampusCourseModelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampusCourseModelId");

                    b.ToTable("CampusCourseNotifications");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusCourseStudent.CampusCourseStudentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CampusCourseModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalResult")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MidtermResult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampusCourseModelId");

                    b.ToTable("CampusCourseStudents");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusCourseTeacher.CampusCourseTeacherModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CampusCourseModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampusCourseModelId");

                    b.ToTable("CampusCourseTeachers");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusGroup.CampusGroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CampusGroups");
                });

            modelBuilder.Entity("Campuscourse.Models.Roles.RolesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Campuscourse.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Campuscourse.Models.Users.BlacklistedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedTokens");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusCourseNotification.CampusCourseNotificationModel", b =>
                {
                    b.HasOne("Campuscourse.Models.CampusCourse.CampusCourseModel", null)
                        .WithMany("Notifications")
                        .HasForeignKey("CampusCourseModelId");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusCourseStudent.CampusCourseStudentModel", b =>
                {
                    b.HasOne("Campuscourse.Models.CampusCourse.CampusCourseModel", null)
                        .WithMany("Students")
                        .HasForeignKey("CampusCourseModelId");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusCourseTeacher.CampusCourseTeacherModel", b =>
                {
                    b.HasOne("Campuscourse.Models.CampusCourse.CampusCourseModel", null)
                        .WithMany("Teachers")
                        .HasForeignKey("CampusCourseModelId");
                });

            modelBuilder.Entity("Campuscourse.Models.Roles.RolesModel", b =>
                {
                    b.HasOne("Campuscourse.Models.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("Campuscourse.Models.Roles.RolesModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Campuscourse.Models.CampusCourse.CampusCourseModel", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Campuscourse.Models.User", b =>
                {
                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
